CREATE TABLE IF NOT EXISTS System (
	EnterPwd TEXT NOT NULL,
	Email TEXT,
	Version INTEGER;
);

CREATE TABLE IF NOT EXISTS Category (
	CatId INTEGER PRIMARY KEY AUTOINCREMENT,
	CatName TEXT NOT NULL,
	CatType INTEGER,
	Remark TEXT
);

CREATE TABLE IF NOT EXISTS Account (
	AcctId INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL,
	LoginName TEXT NOT NULL,
	LoginPwd TEXT NOT NULL,	
	Site TEXT,
	Remark TEXT,
	CatId INTEGER NOT NULL
);
